import type { StorefrontUiLabels } from '@/shared/types/api';

export const STOREFRONT_UI_FIELD_GROUPS: Array<{
  title: string;
  fields: Array<{ key: keyof StorefrontUiLabels; label: string }>;
}> = [
  {
    title: 'Ürün kartları',
    fields: [
      { key: 'productBadgeNew', label: 'Yeni rozeti' },
      { key: 'productBadgeFeatured', label: 'Öne çıkan rozeti' },
      { key: 'productBadgeBestSeller', label: 'Çok satan rozeti' },
      { key: 'productActionDetail', label: 'Detaya git butonu' },
      { key: 'productActionDemo', label: 'Demo butonu' },
      { key: 'productActionBuy', label: 'Satın al butonu' },
      { key: 'productActionDownload', label: 'İndir butonu' },
      { key: 'emptyProducts', label: 'Boş ürün listesi mesajı' },
      { key: 'emptyCategories', label: 'Boş kategori listesi mesajı' },
      { key: 'productNotFound', label: 'Ürün bulunamadı mesajı' },
      { key: 'productListBackLink', label: 'Ürün listesine dön linki' },
      { key: 'productBackLink', label: 'Ürün detay geri linki' },
      { key: 'productAddToCart', label: 'Sepete ekle butonu' },
      { key: 'productAddToCartPending', label: 'Sepete ekleniyor metni' },
      { key: 'productAddToCartError', label: 'Sepete ekleme hata metni' },
      { key: 'productQuantityLabel', label: 'Adet alanı etiketi' },
      { key: 'brandNotFound', label: 'Marka bulunamadı mesajı' },
      { key: 'categoryNotFound', label: 'Kategori bulunamadı mesajı' },
    ],
  },
  {
    title: 'Blog',
    fields: [
      { key: 'emptyBlog', label: 'Boş blog grid mesajı' },
      { key: 'blogIndexEmpty', label: 'Blog listesi boş mesajı' },
      { key: 'readingTimeSuffix', label: 'Okuma süresi eki (ör. dk okuma)' },
      { key: 'blogBackLink', label: 'Blog yazısı geri linki' },
      { key: 'blogPostNotFoundMessage', label: 'Blog yazısı bulunamadı başlığı' },
      { key: 'blogPostNotFoundBackLink', label: 'Blog yazısı bulunamadı geri linki' },
      { key: 'blogNotFoundMessage', label: 'Blog bulunamadı mesajı' },
      { key: 'blogNotFoundBackLink', label: 'Blog bulunamadı geri linki' },
    ],
  },
  {
    title: 'Sayfa ve hata durumları',
    fields: [
      { key: 'notFoundMessage', label: '404 sayfa mesajı' },
      { key: 'notFoundHomeLink', label: '404 ana sayfa linki' },
      { key: 'pageNotFoundTitle', label: 'CMS sayfa bulunamadı başlığı' },
      { key: 'pageNotFoundMessage', label: 'CMS sayfa bulunamadı mesajı' },
      { key: 'pageNotFoundHomeLink', label: 'CMS sayfa bulunamadı linki' },
    ],
  },
  {
    title: 'İletişim formu',
    fields: [
      { key: 'contactFormLoading', label: 'Form yükleniyor metni' },
      { key: 'contactFormNotFound', label: 'Form bulunamadı mesajı' },
      { key: 'contactFormError', label: 'Form gönderim hata metni' },
      { key: 'contactFormSubmitting', label: 'Form gönderiliyor metni' },
      { key: 'formSelectPlaceholder', label: 'Select boş seçenek metni' },
      { key: 'contactBackLink', label: 'İletişim sayfası geri linki' },
    ],
  },
  {
    title: 'Sepet ve sipariş',
    fields: [
      { key: 'cartEmpty', label: 'Boş sepet mesajı' },
      { key: 'cartBackLink', label: 'Sepet geri linki' },
      { key: 'cartCheckoutButton', label: 'Ödemeye geç butonu' },
      { key: 'checkoutBackLink', label: 'Ödeme geri linki' },
      { key: 'orderNotFound', label: 'Sipariş bulunamadı mesajı' },
      { key: 'orderSuccessHomeLink', label: 'Sipariş başarı ana sayfa linki' },
      { key: 'orderTrackingNotFound', label: 'Sipariş takip bulunamadı mesajı' },
      { key: 'orderTrackingNoShipment', label: 'Kargo bilgisi yok mesajı' },
      { key: 'orderTrackingBackLink', label: 'Sipariş takip geri linki' },
    ],
  },
  {
    title: 'Katalog listeleme',
    fields: [
      { key: 'catalogSortFeatured', label: 'Sıralama: öne çıkan' },
      { key: 'catalogSortNewest', label: 'Sıralama: en yeni' },
      { key: 'catalogSortPriceAsc', label: 'Sıralama: fiyat artan' },
      { key: 'catalogSortPriceDesc', label: 'Sıralama: fiyat azalan' },
      { key: 'catalogEmpty', label: 'Filtreye uygun ürün yok mesajı' },
      { key: 'catalogLoading', label: 'Katalog yükleniyor metni' },
      { key: 'catalogResultsSuffix', label: 'Sonuç sayısı eki (ör. sonuç)' },
    ],
  },
  {
    title: 'Sepet detay',
    fields: [
      { key: 'cartQuantityLabel', label: 'Adet etiketi' },
      { key: 'cartRemoveLabel', label: 'Kaldır butonu' },
      { key: 'cartSummaryTitle', label: 'Özet başlığı' },
      { key: 'cartSubtotal', label: 'Ara toplam' },
      { key: 'cartTax', label: 'KDV' },
      { key: 'cartTotal', label: 'Toplam' },
    ],
  },
  {
    title: 'Ödeme sayfası',
    fields: [
      { key: 'checkoutContactTitle', label: 'İletişim bölüm başlığı' },
      { key: 'checkoutNameLabel', label: 'Ad soyad etiketi' },
      { key: 'checkoutEmailLabel', label: 'E-posta etiketi' },
      { key: 'checkoutPhoneLabel', label: 'Telefon etiketi' },
      { key: 'checkoutNoteLabel', label: 'Sipariş notu etiketi' },
      { key: 'checkoutPaymentTitle', label: 'Ödeme bölüm başlığı' },
      { key: 'checkoutNoPaymentMethods', label: 'Ödeme yöntemi yok mesajı' },
      { key: 'checkoutTestMode', label: 'Test modu etiketi' },
      { key: 'checkoutBankAccountsTitle', label: 'Banka hesapları başlığı' },
      { key: 'checkoutBankAccountCount', label: 'Banka hesabı sayısı ({count})' },
      { key: 'checkoutSubmit', label: 'Siparişi tamamla butonu' },
      { key: 'checkoutSubmitPending', label: 'Sipariş oluşturuluyor metni' },
      { key: 'checkoutOrderSummary', label: 'Sipariş özeti başlığı' },
      { key: 'checkoutCouponLabel', label: 'Kupon etiketi' },
      { key: 'checkoutCouponPlaceholder', label: 'Kupon placeholder' },
      { key: 'checkoutCouponApply', label: 'Kupon uygula butonu' },
      { key: 'checkoutCouponRemove', label: 'Kupon kaldır butonu' },
      { key: 'checkoutCouponApplied', label: 'Kupon uygulandı mesajı' },
      { key: 'checkoutCouponError', label: 'Kupon hata mesajı' },
      { key: 'checkoutSubtotal', label: 'Ara toplam' },
      { key: 'checkoutTax', label: 'KDV' },
      { key: 'checkoutDiscount', label: 'İndirim' },
      { key: 'checkoutTotal', label: 'Toplam' },
      { key: 'checkoutErrorGeneric', label: 'Genel sipariş hatası' },
      { key: 'checkoutPaymentRequired', label: 'Ödeme yöntemi seçin mesajı' },
    ],
  },
  {
    title: 'Sipariş başarı / takip',
    fields: [
      { key: 'orderNumberLabel', label: 'Sipariş numarası etiketi' },
      { key: 'orderBankTransferTitle', label: 'Havale bilgileri başlığı' },
      { key: 'orderBankTransferHint', label: 'Havale açıklama metni' },
      { key: 'orderBranchLabel', label: 'Şube etiketi' },
      { key: 'orderTrackingTitle', label: 'Kargo takibi başlığı' },
      { key: 'orderTrackingNumberLabel', label: 'Takip no etiketi' },
      { key: 'orderTrackShipment', label: 'Kargoyu takip et linki' },
      { key: 'orderSummaryTitle', label: 'Sipariş özeti başlığı' },
      { key: 'orderTotalLabel', label: 'Toplam etiketi' },
      { key: 'orderTrackLink', label: 'Siparişi takip et linki' },
      { key: 'orderContinueShopping', label: 'Alışverişe devam linki' },
      { key: 'orderTrackingFormNumberLabel', label: 'Takip form sipariş no' },
      { key: 'orderTrackingFormNumberPlaceholder', label: 'Takip form no placeholder' },
      { key: 'orderTrackingFormEmailLabel', label: 'Takip form e-posta' },
      { key: 'orderTrackingFormEmailPlaceholder', label: 'Takip form e-posta placeholder' },
      { key: 'orderTrackingFormSubmit', label: 'Takip form sorgula butonu' },
      { key: 'orderTrackingShipmentTitle', label: 'Kargo bilgisi başlığı' },
      { key: 'orderTrackingCarrierLabel', label: 'Kargo firması etiketi' },
      { key: 'orderTrackingNumberFieldLabel', label: 'Takip numarası etiketi' },
    ],
  },
  {
    title: 'Katalog filtreleri',
    fields: [
      { key: 'catalogFiltersTitle', label: 'Filtreler başlığı' },
      { key: 'catalogFilterButton', label: 'Filtrele butonu' },
      { key: 'catalogGridView', label: 'Izgara görünüm' },
      { key: 'catalogListView', label: 'Liste görünüm' },
      { key: 'catalogPrev', label: 'Önceki' },
      { key: 'catalogNext', label: 'Sonraki' },
      { key: 'catalogCloseFilters', label: 'Filtreleri kapat' },
      { key: 'catalogShowResults', label: 'Sonuçları göster' },
      { key: 'catalogSearchLabel', label: 'Arama etiketi' },
      { key: 'catalogSearchPlaceholder', label: 'Arama placeholder' },
      { key: 'catalogCategoryLabel', label: 'Kategori etiketi' },
      { key: 'catalogAllOption', label: 'Tümü seçeneği' },
      { key: 'catalogBrandLabel', label: 'Marka etiketi' },
      { key: 'catalogPriceRangeLabel', label: 'Fiyat aralığı' },
      { key: 'catalogPriceMin', label: 'Min fiyat' },
      { key: 'catalogPriceMax', label: 'Max fiyat' },
      { key: 'catalogProductCountSuffix', label: 'Ürün sayısı ({count} ürün)' },
    ],
  },
  {
    title: 'Ürün detay / sepet modal',
    fields: [
      { key: 'productAttributesTitle', label: 'Ürün özellikleri başlığı' },
      { key: 'productVariantOutOfStock', label: 'Varyant stokta yok' },
      { key: 'productVariantStock', label: 'Stok metni ({qty})' },
      { key: 'productVariantUnavailable', label: 'Kombinasyon yok mesajı' },
      { key: 'cartAddedTitle', label: 'Sepete eklendi başlığı' },
      { key: 'cartAddedQuantity', label: 'Sepete eklendi adet ({qty})' },
      { key: 'cartAddedTotal', label: 'Sepetteki toplam ürün ({count})' },
      { key: 'cartAddedGoToCart', label: 'Sepete git butonu' },
      { key: 'cartAddedContinue', label: 'Alışverişe devam butonu' },
    ],
  },
  {
    title: 'Yorumlar',
    fields: [
      { key: 'reviewsTitle', label: 'Yorumlar başlığı' },
      { key: 'reviewsCount', label: 'Yorum sayısı ({count})' },
      { key: 'reviewsEmpty', label: 'Boş yorum mesajı' },
      { key: 'reviewsLoading', label: 'Yorumlar yükleniyor' },
      { key: 'reviewsStoreReply', label: 'Mağaza cevabı etiketi' },
      { key: 'reviewsWriteTitle', label: 'Yorum yaz başlığı' },
      { key: 'reviewsModerationNote', label: 'Moderasyon notu' },
      { key: 'reviewsThankYou', label: 'Teşekkür mesajı' },
      { key: 'reviewsRatingLabel', label: 'Puan etiketi' },
      { key: 'reviewsNameLabel', label: 'Ad etiketi' },
      { key: 'reviewsEmailLabel', label: 'E-posta etiketi' },
      { key: 'reviewsTitleLabel', label: 'Başlık etiketi' },
      { key: 'reviewsCommentLabel', label: 'Yorum etiketi' },
      { key: 'reviewsSubmit', label: 'Gönder butonu' },
      { key: 'reviewsSubmitPending', label: 'Gönderiliyor metni' },
      { key: 'reviewsSubmitError', label: 'Gönderim hata mesajı' },
      { key: 'reviewsPrev', label: 'Önceki' },
      { key: 'reviewsNext', label: 'Sonraki' },
    ],
  },
];
